"""empty message

Revision ID: 326c1072f1e9
Revises: 71027c4ff149
Create Date: 2023-07-22 18:53:43.736970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326c1072f1e9'
down_revision = '71027c4ff149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('answer_Mult',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('answer_Mult',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
