"""empty message

Revision ID: 4e2e4de7ad27
Revises: c4a9637f4c64
Create Date: 2023-07-21 20:14:54.673074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2e4de7ad27'
down_revision = 'c4a9637f4c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_question', schema=None) as batch_op:
        batch_op.drop_column('nota')

    # ### end Alembic commands ###
