"""empty message

Revision ID: 563f95b18705
Revises: 607faad01d65
Create Date: 2023-07-09 15:36:41.489762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563f95b18705'
down_revision = '607faad01d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testes')
    # ### end Alembic commands ###
