"""empty message

Revision ID: 607faad01d65
Revises: 8e8848165dfc
Create Date: 2023-07-09 15:03:23.101996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607faad01d65'
down_revision = '8e8848165dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
